### ISSUE TITLE
Issue with receiving logs on Vercel

### ISSUE THREAD

**Issue by slugb0t** [oscard0m/example-probot-vercel-ts#18]
Hi, I'm using this template as a guide to upload my Probot app to Vercel. I'm wondering as to why I'm not receiving any logs of the actions the github app does (ex: when I install the app no logs are sent to vercel of the action)
I set up probot actions correctly but I believe it has to do with the configurations/settings of Vercel and the Github app.
I configured my github app's webhook url to be https://<my-app>.vercel.app/api/github/webhooks and have my build and development settings configured properly as well.
Any help would be appreciated! Thank you

**Comment by oscard0m** [comment]
Hi @slugb0t!

I'm sorry for the delay in answering. Would it be possible to re-create a public repository where I could see the code?

**Comment by slugb0t** [comment]
Hey! No worries, I ended solving the issue. I was creating a Probot instance when trying to pass it onto the nodeMiddleWare. I appreciate the reach out though.
Have a nice day!

**Comment by oscard0m** [comment]
> Hey! No worries, I ended solving the issue. I was creating a Probot instance when trying to pass it onto the nodeMiddleWare. I appreciate the reach out though.
> 
> Have a nice day!

I'm glad you could by-pass the issue. Have a good day as well
